env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

snapshot:
  name_template: '{{ incpatch .Version }}-next'

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=wroge

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
  - image_templates:
      - 'wroge/wms:latest'
      - 'wroge/wms:{{ .Tag }}'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

brews:
  - tap:
      owner: wroge
      name: homebrew-tap
    homepage:  https://github.com/wroge/wms
    description: A command-line-tool to simplify the use of Web Map Services.
    license: MIT

scoop:
  bucket:
    owner: wroge
    name: scoop-bucket
  homepage:  https://github.com/wroge/wms
  description: A command-line-tool to simplify the use of Web Map Services.
  license: MIT
