version: 2
before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cli
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=wroge
    id: lin

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: ['binary']
    files:
      - README.md
      - LICENSE

brews:
  - homepage: 'https://github.com/sgaunet/wms'
    description: ''
    directory: Formula
    commit_author:
      name: sgaunet
      email: 1552102+sgaunet@users.noreply.github.com
    repository:
      owner: sgaunet
      name: homebrew-tools
      # Token with 'repo' scope is required for pushing to a different repository
      token: '{{ .Env.HOMEBREW_TAP_TOKEN }}'
    url_template: 'https://github.com/sgaunet/wms/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    install: |
      bin.install "{{ .ArtifactName }}" => "wms"
    test: |
      system "#{bin}/wms", "--help"

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    # extra_files:
    # - src
    # - resources

  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    # extra_files:
    # - src
    # - resources

  - use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-armv6"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-armv6"
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    # extra_files:
    # - src
    # - resources

  - use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-armv7"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    # extra_files:
    # - src
    # - resources

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: ghcr.io/sgaunet/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-amd64
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-arm64v8
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-armv6
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-armv7