# https://taskfile.dev
version: '3'
vars:
  BINFILE: wms

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - CGO_ENABLED=0 go build -o {{.BINFILE}} cli/*.go

  tests:
    dir: tests
    cmds:
      - venom run tests.yml --output-dir="log" --stop-on-failure

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean